### PR TITLE
more slim Debian based image

### PR DESCRIPTION
**Pull request by zchee**
more slim Debian based images.

Added `--no-install-recommends` and `--no-install-suggests` flags to `apt-get` command. It might be more slim image size.

### CODE REVIEW

**Comment by ahmetb** [comment]
Does Dockerfile build fine on your machine? I get error:


```
Download error on https://pypi.python.org/simple/pip/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581) -- Some packages may not be found!
Couldn't find index page for 'pip' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
Download error on https://pypi.python.org/simple/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581) -- Some packages may not be found!
No local packages or download links found for pip
error: Could not find suitable distribution for Requirement.parse('pip')
```

**Comment by zchee** [comment]
@ahmetb Ah, sorry. I'd check `docker build` but something went wrong.
Added `ca-cartificate` package for `easy_install -U pip`.

Also, Normally some base images clear `apt` list cache after `apt-get`. like https://github.com/docker-library/golang/blob/cf5669b0a1d3411c32896075bfabebafda12adbf/1.8/jessie/Dockerfile#L10
So, I also added `rm -rf /var/lib/apt/lists/*` command after the installed all packages.

As a result, `google/cloud-sdk` image size is,

```sh
REPOSITORY                   TAG                 IMAGE ID            CREATED             SIZE
google/cloud-sdk            latest              e226ddb12871        4 days ago          1.64GB
zchee/cloud-sdk             latest              f328153cc7f5        9 seconds ago       1.54GB
google/cloud-sdk            slim                12a7148e8de0        4 days ago          543MB
zchee/cloud-sdk             slim                64329657bd0e        11 minutes ago      521MB
```

PTAL.

**Comment by ahmetb** [comment]
We actually can't `rm -rf /var/lib/apt/lists/*` as we recommend people to extend this image by using it as a base image, then running `apt-get install`. Removing the apt cache would break such users.

It looks like the improvements in this PR are 5-6%, I'm thinking it might not be really worth taking the risk to break downstream users taking this as a base image.

**Comment by zchee** [comment]
@ahmetb I see. I totally agreed your opinions.
Should I close this pull request? or, you pointed only if clear apt cache?

**Comment by ahmetb** [comment]
I'll close, thanks!

**Comment by zchee** [comment]
@ahmetb Thanks for discuss :D

**Pull request closed without merging**
