### PR TITLE
Update SDK to 197.0.0

### PR DESCRIPTION
**Pull request by nrvnrvn**

### CODE REVIEW

**Comment by ahmetb** [comment]
Hi, do you need this release specifically? Or are you just trying to keep it up to date?

**Comment by nrvnrvn** [comment]
Hi! Just trying to keep it up :) noticed that local sdk version is newer than the image we are using as a parent one.

**Comment by ahmetb** [comment]
We release new Docker image versions on a best effort basis. So unless you absolutely need, I'll hold off on this one (and release it myself). Most of the time we recommend you stick to a version of the gcloud image that works and keep using that instead of using :latest.

**Comment by nrvnrvn** [comment]
Is there a reason for not syncing docker image releases with actual google cloud sdk releases (using automated CI/CD pipelines for example)?

We are using gcloud locally following the release cycle and updating it and considered using official google cloud sdk docker images. In order to keep things consistent we need to decide whether to stick to official images or maintain the SDK image on our own. 

We don't use the `:latest` tag btw. In case of this repo it would be `:alpine`

**Comment by ahmetb** [comment]
Skipping this version. I just pushed tagged v198.0.0.
Thanks for your PR. Next time you can just open an issue and I'll bump the version.

**Pull request closed without merging**
