### PR TITLE
Add cloud-datastore-emulator and app-engine-go components

### LINKED ISSUE #42: Components cloud-datastore-emulator and app-engine-go not installed
README.md says 

> google/cloud-sdk is a Docker image bundling all the components and dependencies of the Google Cloud SDK including alpha and beta components.

However, google/cloud-sdk image is missing the components app-engine-go and cloud-datastore-emulator.

```
docker run google/cloud-sdk gcloud components list                            

Your current Cloud SDK version is: 119.0.0
The latest available version is: 119.0.0

+------------------------------------------------------------------------------------------+
|                                        Components                                        |
+---------------+-----------------------------------+--------------------------+-----------+
|     Status    |                Name               |            ID            |    Size   |
+---------------+-----------------------------------+--------------------------+-----------+
| Not Installed | Cloud Datastore Emulator          | cloud-datastore-emulator |  16.1 MiB |
| Not Installed | gcloud app Go Extensions          | app-engine-go            |   1.5 MiB |
| Installed     | BigQuery Command Line Tool        | bq                       |   < 1 MiB |
| Installed     | Cloud Datastore Emulator (Legacy) | gcd-emulator             |  38.1 MiB |
| Installed     | Cloud Pub/Sub Emulator            | pubsub-emulator          |  10.8 MiB |
| Installed     | Cloud SDK Core Libraries          | core                     |   4.0 MiB |
| Installed     | Cloud Storage Command Line Tool   | gsutil                   |   2.6 MiB |
| Installed     | Default set of gcloud commands    | gcloud                   |           |
| Installed     | gcloud Alpha Commands             | alpha                    |   < 1 MiB |
| Installed     | gcloud Beta Commands              | beta                     |   < 1 MiB |
| Installed     | gcloud app Java Extensions        | app-engine-java          | 131.0 MiB |
| Installed     | gcloud app Python Extensions      | app-engine-python        |   7.2 MiB |
| Installed     | kubectl                           | kubectl                  |   8.2 MiB |
+---------------+-----------------------------------+--------------------------+-----------+
To install or remove components at your current SDK version [119.0.0], run:
  $ gcloud components install COMPONENT_ID
  $ gcloud components remove COMPONENT_ID

To update your SDK installation to the latest version [119.0.0], run:
  $ gcloud components update

```

Trying to install them results in an error:

```
docker run google/cloud-sdk gcloud components install cloud-datastore-emulator

You cannot perform this action because this Cloud SDK installation is 
managed by an external package manager.  If you would like to get the 
latest version, please see our main download page at:
  
https://cloud.google.com/sdk/

ERROR: (gcloud.components.install) The component manager is disabled for this installation
```

### PR DESCRIPTION
**Pull request by ckeeney**
Added components 
 - cloud-datastore-emulator
 - app-engine-go

This closes #42

### CODE REVIEW

**Comment by shilov** [comment]
Came here hoping to see this. Would be nice to see this merged so we don't have to maintain our own fork.

**Comment by tswast** [comment]
Thanks for your contribution!

I'm wondering what you are using this project for? I need to find who owns the Docker image and convince them it's worth rebuilding a new version.

**Comment by ckeeney** [comment]
I wanted to setup a development environment using Google Datastore emulator and docker-compose, hence the need for the cloud-datastore-emulator component.

Yes, I agree this package could use a bit more active maintenance.  Fortunately the image on docker hub is set to automatically build upon merges into master so I think it should just happen.

**Comment by email2liyang** [comment]
I try to start the cloud-datastore emulator inside docker with command  below, seems I can't access it from the host machine
```
 docker run -p 8000:8000 --name gcd google/cloud-sdk gcloud beta emulators datastore start --project=pi-docker --host-port 127.0.0.1:8000 --no-store-on-disk
```
the docker image can start without problem. , but when I try go access it from host machine, it get empty response,and our google datastore java client can't communicate with the docker instance via port 8000
```
curl localhost:8000
curl: (52) Empty reply from server
```

docker container log below.
```
Executing: /google-cloud-sdk/platform/cloud-datastore-emulator/cloud_datastore_emulator create --project_id=pi-docker /.config/gcloud/emulators/datastore
[datastore] Sep 20, 2016 4:22:23 AM com.google.cloud.datastore.emulator.CloudDatastore$CreateAction$1 apply
[datastore] INFO: Provided project_id to Cloud Datastore emulator create command, which is no longer necessary.
[datastore] Created new Cloud Datastore project in '/.config/gcloud/emulators/datastore'.
Executing: /google-cloud-sdk/platform/cloud-datastore-emulator/cloud_datastore_emulator start --host=127.0.0.1 --port=8000 --store_on_disk=False --consistency=0.9 --allow_remote_shutdown /.config/gcloud/emulators/datastore
[datastore] Sep 20, 2016 4:22:23 AM com.google.cloud.datastore.emulator.CloudDatastore$FakeDatastoreAction$7 apply
[datastore] INFO: Provided --allow_remote_shutdown to start command which is no longer necessary.
[datastore] Sep 20, 2016 4:22:23 AM com.google.cloud.datastore.emulator.impl.LocalDatastoreFileStub <init>
[datastore] INFO: Local Datastore initialized:
[datastore] 	Type: High Replication
[datastore] 	Storage: In-memory
[datastore] Sep 20, 2016 4:22:23 AM io.grpc.internal.ManagedChannelImpl <init>
[datastore] INFO: [ManagedChannelImpl@1409d7f5] Created with target 127.0.0.1:8000
[datastore] Sep 20, 2016 4:22:24 AM io.gapi.emulators.netty.NettyUtil applyJava7LongHostnameWorkaround
[datastore] INFO: Applied Java 7 long hostname workaround.
[datastore] API endpoint: http://127.0.0.1:8000
[datastore] If you are using a library that supports the DATASTORE_EMULATOR_HOST environment variable, run:
[datastore] 
[datastore]   export DATASTORE_EMULATOR_HOST=127.0.0.1:8000
[datastore] 
[datastore] Dev App Server is now running.
[datastore] 
```

inside docker container, it has no problem at all to access the service
```
 docker exec -it gcd wget localhost:8000
converted 'http://localhost:8000' (ANSI_X3.4-1968) -> 'http://localhost:8000' (UTF-8)
--2016-09-20 04:48:16--  http://localhost:8000/
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:8000... failed: Connection refused.
Connecting to localhost (localhost)|127.0.0.1|:8000... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3
Saving to: 'index.html'

index.html                                   100%[==============================================================================================>]       3  --.-KB/s   in 0s     

2016-09-20 04:48:16 (30.7 KB/s) - 'index.html' saved [3/3]
```

**Comment by email2liyang** [comment]
@tswast should I open an issue to track this ?

**Comment by tswast** [comment]
Yes, please open an issue. Note: maintenance of this repo is limited. I'm happy to accept pull requests, but may not have time to debug myself.

**Comment by email2liyang** [comment]
@tswast , I have created issue in https://github.com/GoogleCloudPlatform/cloud-sdk-docker/issues/49.
@ckeeney did you meet such issue described issue #49?

**Comment by ckeeney** [comment]
@tswast if you are comfortable with it I would be happy to take on some of the maintenance burden if I was added as a maintainer.

@email2liyang no I did not encounter such an issue, but I actually never got around to trying out the datastore emulator.  I do think I understand your problem.  Let's continue the discussion at #49.

**Pull request merged**
