### PR TITLE
Document CLOUDSDK_ environment variables

### PR DESCRIPTION
**Pull request by remcohaszing**
This is a bit of a hidden option of the Google Cloud SDK, although some explicit use cases are mentioned in the documentation.

I think this is especially useful in CI.

### CODE REVIEW

**Comment by willfaris** [comment]
In general we would like to reference the main documentation for the product rather than duplicate it. I believe this link will work

https://cloud.google.com/sdk/docs/properties#setting_properties_via_environment_variables

What do you think of changing this to be something like

You can set any Cloud SDK property via an ENV, please  see https://cloud.google.com/sdk/docs/properties#setting_properties_via_environment_variables

**Comment by gerbercj** [comment]
There is also a related documentation addition coming tomorrow to the following page:
https://cloud.google.com/sdk/gcloud/reference/config

```
    In addition to setting properties in a configuration, and the use of flags,
    it is possible to override the value of a property with an environment
    variable. The matching environment variable for a property is of the form
    'CLOUDSDK_CATEGORY_PROPERTY'. For example, to demonstrate overriding the
    project property in the core category to my-project, use a command like:

        $ CLOUDSDK_CORE_PROJECT=my-project gcloud config get-value \
            core/project
```

**Comment by remcohaszing** [comment]
I gave feedback I couldn’t find it on https://cloud.google.com/sdk/gcloud/reference/config / `man gcloud_config`. I’m glad this is being worked on. I mainly created this pull request because I can contribute here, but not on the man pages (afaik). I didn’t find https://cloud.google.com/sdk/docs/properties though, I was mainly searching for `gcloud config`.

I agree it’s not ideal to duplicate documentation, but I do think CI (often using this Docker image) is the main reason for using environment variables, so I’ll apply the suggestion by @willfaris

**Comment by willfaris** [comment]
The content gerbercj pointed out is not live just yet...  I am going to merge this and I will change the link to the new content as soon as it is live today.

**Pull request merged**
