### PR TITLE
Add crcmod to dependencies

### PR DESCRIPTION
**Pull request by ishitatsuyuki**
This speeds up gsutil operations.

### CODE REVIEW

**Comment by ishitatsuyuki** [comment]
I signed it!

**Comment by ishitatsuyuki** [comment]
Turns out this requires an up-to-date Debian base image, which should have backports enabled.

**Comment by ahmetb** [comment]
@ishitatsuyuki have you tested if this actually solves the missing crcmod problem? Last time I tried myself it didn't take any effect this way. The way we install this in `gcr.io/cloud-builders/gcloud` image is through pip: 

https://github.com/GoogleCloudPlatform/cloud-builders/blob/4d53db7f29185e74f8e8c490b8cac9d547694b58/gcloud/Dockerfile#L25-L26

**Comment by ishitatsuyuki** [comment]
@ahmetb the current configuration in this PR doesn't work, since the old Debian package has only crcmod without native accelerators.

However, I have tested with the backports repository enabled (https://github.com/ishitatsuyuki/cloud-sdk-docker/commit/33618ab710b40aa5e76d685962d30275a607da66), and it works as intended. The link you mentioned use Ubuntu, which will contain the native extension if upgraded to Xenial.

**Comment by ahmetb** [comment]
@salrashid123 we should take care of this once your PR #68 is merged.

**Comment by salrashid123** [comment]
@ahmetb @ishitatsuyuki 

ok, taking suggestion on how to best add in crcmod to debian, centos images we'll have (atleast documented).

What we can do is basically run through the install with gcc, setuptools, etc which will make those images a bit larger...

- [https://cloud.google.com/storage/docs/gsutil/addlhelp/CRC32CandInstallingcrcmod#installation](https://cloud.google.com/storage/docs/gsutil/addlhelp/CRC32CandInstallingcrcmod#installation)
 
Alpine has a package so  i can use that there:
- [https://pkgs.alpinelinux.org/package/edge/community/x86_64/py-crcmod](https://pkgs.alpinelinux.org/package/edge/community/x86_64/py-crcmod)

**Comment by ahmetb** [comment]
@salrashid123 please check how cloud-builders/gcloud image does that. if we were to install gcc/setuptools etc, we should uninstall them before completing the RUN step.

**Comment by ahmetb** [comment]
This fixed in #68.

**Pull request closed without merging**
